# Generated by Django 4.2.3 on 2024-12-12 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(null=True)),
                ('run_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255, unique=True)),
                ('lead_type', models.CharField(choices=[('Hot Lead', 'Hot Lead'), ('Warm Lead', 'Warm Lead'), ('Information Seeker', 'Information Seeker'), ('Cold Lead', 'Cold Lead'), ('Uncertain', 'Uncertain')], default='Uncertain', max_length=20)),
                ('lead_reson', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.contact')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatresponse')),
            ],
        ),
    ]
