# Generated by Django 4.2.3 on 2024-12-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_thread_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.contact'),
        ),
    ]
