# Generated by Django 4.2.3 on 2024-12-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chatrequest_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
    ]
