# Generated by Django 4.2.3 on 2024-12-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_thread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
