# Generated by Django 4.2.3 on 2024-12-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='test_number',
            field=models.BooleanField(default=False),
        ),
    ]
