# Generated by Django 4.2.3 on 2025-01-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_oauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lead_reson',
            new_name='lead_reason',
        ),
    ]
