# Generated by Django 4.2.3 on 2025-01-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_rename_lead_reson_contact_lead_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('pricing_type', models.CharField(max_length=255)),
                ('count', models.SmallIntegerField()),
            ],
        ),
    ]
