# Generated by Django 4.2.3 on 2025-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_clubclass_clubprogram_programschedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programschedule',
            name='unique_program_schedule',
        ),
        migrations.AddField(
            model_name='programschedule',
            name='specialization_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='programschedule',
            constraint=models.UniqueConstraint(fields=('program', 'start_time', 'end_time', 'specialization_id'), name='unique_program_schedule'),
        ),
    ]
