# Generated by Django 4.2.3 on 2025-02-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_remove_programschedule_unique_program_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programschedule',
            name='unique_program_schedule',
        ),
        migrations.RemoveField(
            model_name='programschedule',
            name='specialization_id',
        ),
    ]
