# Generated by Django 4.2.3 on 2025-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_remove_programschedule_unique_program_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='class_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
