# Generated by Django 4.2.3 on 2025-02-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_programschedule_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reason_of_approach',
            field=models.CharField(choices=[('Adult Membership', 'Adult Membership'), ('Junior Membership', 'Junior Membership')], max_length=40, null=True),
        ),
    ]
