# Generated by Django 4.2.3 on 2025-02-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_contact_reason_of_approach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubprogram',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='programschedule',
            name='program',
        ),
        migrations.DeleteModel(
            name='ClubClass',
        ),
        migrations.DeleteModel(
            name='ClubProgram',
        ),
        migrations.DeleteModel(
            name='ProgramSchedule',
        ),
    ]
