# Generated by Django 4.2.3 on 2025-02-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_remove_clubprogram_class_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingCall',
        ),
        migrations.AddField(
            model_name='chatresponse',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
