# Generated by Django 4.2.3 on 2025-02-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_delete_pricingcall_chatresponse_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatresponse',
            name='replied',
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
