# Generated by Django 4.2.3 on 2025-02-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_remove_chatresponse_replied_chatrequest_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequest',
            name='replied',
        ),
    ]
