# Generated by Django 4.2.3 on 2025-02-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_remove_chatrequest_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='conversation_closed',
            field=models.BooleanField(default=False),
        ),
    ]
