# Generated by Django 4.2.3 on 2025-02-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_chatrequest_conversation_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequest',
            name='conversation_closed',
        ),
        migrations.AddField(
            model_name='contact',
            name='conversation_closed',
            field=models.BooleanField(default=False),
        ),
    ]
