# Generated by Django 4.2.3 on 2025-03-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_remove_chatrequest_conversation_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('conversation_type', models.CharField(choices=[('Human', 'Human'), ('AI', 'AI')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='thread',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='response',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='conversation_closed',
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='error_message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChatResponse',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.AddField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.contact'),
        ),
    ]
