# Generated by Django 4.2.3 on 2025-03-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0023_conversation_remove_thread_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('Human', 'Human'), ('AI', 'AI'), ('ToolCall', 'ToolCall')], max_length=20, null=True),
        ),
    ]
