# Generated by Django 4.2.3 on 2025-03-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0027_toolcall_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcall',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
